export const CART_ACTION_TYPES = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  INCREMENT_PRODUCT_COUNT: "INCREMENT_PRODUCT_COUNT",
  DECREMENT_PRODUCT_COUNT: "DECREMENT_PRODUCT_COUNT",
  GET_TOTAL_AMOUNT: "GET_TOTAL_AMOUNT",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  TOGGLE_CART: "TOGGLE_CART",
};
