export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORY_MAP: "SET_CATEGORY_MAP",
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "FETCH_CATEGORIES_FAILED",
};
